version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.multi-stage
    container_name: badminton-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads
      - backend_logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - badminton_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: badminton-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - badminton_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  backend_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./uploads
  backend_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs

networks:
  badminton_network:
    driver: bridge 