apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: badminton-journey
  labels:
    app.kubernetes.io/name: badminton-journey
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast-ssd  # 根据集群配置调整
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: badminton-journey
  labels:
    app.kubernetes.io/name: badminton-journey
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: fast-ssd  # 根据集群配置调整
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: badminton-journey
  labels:
    app.kubernetes.io/name: badminton-journey
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany  # 多个Pod需要共享上传文件
  resources:
    requests:
      storage: 100Gi
  storageClassName: shared-storage  # 需要支持ReadWriteMany的存储类
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: badminton-journey
  labels:
    app.kubernetes.io/name: badminton-journey
    app.kubernetes.io/component: logs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: shared-storage 