apiVersion: v1
kind: Secret
metadata:
  name: badminton-secrets
  namespace: badminton-journey
  labels:
    app.kubernetes.io/name: badminton-journey
    app.kubernetes.io/component: config
type: Opaque
data:
  # 数据库密码 (badminton123)
  DB_USER: YmFkbWludG9u
  DB_PASSWORD: YmFkbWludG9uMTIz
  DB_ROOT_PASSWORD: QmFkbWludG9uSm91cm5leTIwMjMh
  
  # JWT密钥 (base64 encoded)
  JWT_SECRET: VGhpc0lzQVZlcnlMb25nU2VjcmV0S2V5Rm9yQmFkbWludG9uSm91cm5leUFwcGxpY2F0aW9uMjAyMyFAIyQlXiYqKClfKzEyMzQ1Njc4OTA=
---
# 创建一个用于示例的TLS证书secret（生产环境需要真实证书）
apiVersion: v1
kind: Secret
metadata:
  name: badminton-tls
  namespace: badminton-journey
  labels:
    app.kubernetes.io/name: badminton-journey
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # 这里需要替换为真实的证书和私钥（base64编码）
  # 示例：自签名证书，生产环境请使用真实证书
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t 