spring:
  application:
    name: badminton-journey
  
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-service}:${DB_PORT:3306}/${DB_NAME:badminton_journey}?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:badminton}
    password: ${DB_PASSWORD:badminton123}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Shanghai
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:1024MB}
      max-request-size: ${MAX_FILE_SIZE:1024MB}

  # Jackson配置
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      read-unknown-enum-values-as-null: true
    mapper:
      accept-case-insensitive-enums: true

  # Redis配置
  redis:
    host: ${REDIS_HOST:redis-service}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-connections: 8192

# JWT配置
jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongSecretKeyForBadmintonJourneyApplication2023!@#$%^&*()_+1234567890}
  expiration: 86400000 # 24 hours

# 文件上传配置
file:
  upload-dir: ${UPLOAD_DIR:/app/uploads}
  allowed-extensions: jpg,jpeg,png,gif,mp4,avi,mov

# CORS配置
cors:
  allowed-origins: ${ALLOWED_ORIGINS:*}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# 日志配置
logging:
  level:
    com.badmintonjourney: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.hibernate: WARN
    org.springframework.web: INFO
  file:
    name: /app/logs/badminton-journey.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Kubernetes特定配置
kubernetes:
  namespace: badminton-journey
  pod:
    name: ${HOSTNAME:unknown} 