spring:
  application:
    name: badminton-journey
  
  datasource:
    url: jdbc:h2:file:./data/badminton
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

server:
  port: 8080
  servlet:
    context-path: /api

# JWT配置
jwt:
  secret: badmintonJourneySecretKey2023!@#$%^&*()
  expiration: 86400000 # 24 hours

# 文件上传配置
file:
  upload-dir: ./uploads
  allowed-extensions: jpg,jpeg,png,gif,mp4,avi,mov

# CORS配置
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true 