spring:
  application:
    name: badminton-journey
  
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:badminton_journey}?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:badminton}
    password: ${DB_PASSWORD:badminton123}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Shanghai
  
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  # Jackson配置
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      read-unknown-enum-values-as-null: true
    mapper:
      accept-case-insensitive-enums: true

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# JWT配置
jwt:
  secret: ${JWT_SECRET:ThisIsAVeryLongSecretKeyForBadmintonJourneyApplication2023!@#$%^&*()_+1234567890}
  expiration: 86400000 # 24 hours

# 文件上传配置
file:
  upload-dir: /app/uploads
  allowed-extensions: jpg,jpeg,png,gif,mp4,avi,mov

# CORS配置 - 生产环境更严格
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost,http://localhost:80,https://yourdomain.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# 日志配置
logging:
  level:
    com.badmintonjourney: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  file:
    name: /app/logs/badminton-journey.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized 