spring:
  application:
    name: badminton-journey
  
  datasource:
    url: jdbc:h2:file:/app/data/badminton
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  # Jackson配置
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      read-unknown-enum-values-as-null: true
    mapper:
      accept-case-insensitive-enums: true

server:
  port: 8080
  servlet:
    context-path: /api

# JWT配置
jwt:
  secret: ThisIsAVeryLongSecretKeyForBadmintonJourneyApplication2023!@#$%^&*()_+1234567890
  expiration: 86400000 # 24 hours

# 文件上传配置
file:
  upload-dir: /app/uploads
  allowed-extensions: jpg,jpeg,png,gif,mp4,avi,mov

# CORS配置 - Docker环境允许所有域名
cors:
  allowed-origins: "*"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# 日志配置
logging:
  level:
    com.badmintonjourney: INFO
    org.springframework.security: WARN
  file:
    name: /app/logs/badminton-journey.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 